### PR TITLE
Fix some operations for thecl

### PR DESCRIPTION
**Pull request by muter3000**
Operation 1003 changed arguments from "S" to "", so re-compilation was failing

### CODE REVIEW

**Comment by 32th-System** [comment]
There are also other issues to resolve I think. This is what I get when I try to decompile every ecl file in the game at once
```
> for %f in (*.ecl) do @echo %f && thecl -d185 %f %f.c
boss01.ecl
boss01t.ecl
boss02.ecl
boss03.ecl
boss04.ecl
boss05.ecl
boss06.ecl
boss07.ecl
boss08.ecl
boss09.ecl
boss10.ecl
boss11.ecl
boss12.ecl
boss13.ecl
boss14.ecl
boss15.ecl
boss16.ecl
boss17.ecl
boss18.ecl
boss19.ecl
boss20.ecl
boss21.ecl
boss22.ecl
boss23.ecl
boss24.ecl
boss25.ecl
boss26.ecl
boss27.ecl
default.ecl
thecl: id 1020 was not found in the format table
thecl: (total parameter size is 4)
thecl: id 1020 was not found in the format table
thecl: (total parameter size is 4)
wave01.ecl
wave01t.ecl
wave02.ecl
wave02t.ecl
wave03.ecl
wave03t.ecl
wave04.ecl
wave05.ecl
wave06.ecl
wave07.ecl
wave08.ecl
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
wave09.ecl
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
wave10.ecl
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
wave11.ecl
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
wave12.ecl
wave13.ecl
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
wave14.ecl
wave15.ecl
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
wave16.ecl
wave17.ecl
wave18.ecl
wave19.ecl
wave20.ecl
wave21.ecl
wave22.ecl
wave23.ecl
wave24.ecl
wave25.ecl
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
wave26.ecl
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
wave27.ecl
wave28.ecl
wave29.ecl
wave30.ecl
wave31.ecl
wave32.ecl
wave33.ecl
wave34.ecl
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
wave35.ecl
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
wave36.ecl
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
wave37.ecl
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
wave38.ecl
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
wave39.ecl
wave40.ecl
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
wave41.ecl
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
wave42.ecl
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
wave43.ecl
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
wave44.ecl
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
wave45.ecl
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
wave46.ecl
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
wave47.ecl
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
wave48.ecl
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
wave49.ecl
wave50.ecl
wave51.ecl
wave52.ecl
wave53.ecl
wave54.ecl
wave55.ecl
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
wave56.ecl
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
wave57.ecl
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
wave58.ecl
wave59.ecl
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
wave60.ecl
wave61.ecl
wave62.ecl
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
wave63.ecl
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
wave64.ecl
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
wave65.ecl
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
wave66.ecl
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
wave67.ecl
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
wave68.ecl
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
wave69.ecl
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
wave70.ecl
thecl: id 1026 was not found in the format table
thecl: (total parameter size is 4)
wave71.ecl
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
thecl:value_list_from_data: 16 bytes left over when parsing format "fffff"
wave72.ecl
wave73.ecl
world01.ecl
world01t.ecl
world02.ecl
world03.ecl
world04.ecl
world05.ecl
world06.ecl
world07.ecl
world08.ecl
```

**Comment by muter3000** [comment]
Yeah, working on it right now

**Comment by muter3000** [comment]
Verified that decompilation and compilation is working with:
```sh
for %f in (*.ecl) do @echo %f && thecl -d 185 %f %f.c > out/%f.txt
```
and
```sh
for %f in (*.ecl) do @echo %f && thecl -c 185 %f
```

**Comment by 32th-System** [comment]
confirmed this works

**Pull request merged**
